import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

export async function GET(_req: Request, ctx: { params: Promise<{ jobId: string }> }) {
  const { jobId } = await ctx.params;
  return NextResponse.json({
    code: 0,
    message: "ok",
    data: {
      job_id: decodeURIComponent(jobId),
      title: "Q2 策略汇报（演示）",
      subtitle: "Generated by Eko demo",
      page_count: 3,
      status: "completed",
      progress: 1,
      download_url: null,
      slides: [
        { slide_number: 1, title: "封面", template: "cover" },
        { slide_number: 2, title: "关键结论", template: "bullets" },
        { slide_number: 3, title: "下一步", template: "next" },
      ],
    },
  });
}
